"""add llm analysis

LLM 분석 결과 테이블과 Job 의 분석 상태 컬럼을 추가한다 (Harness §50 / §51).

분석은 Transcript 를 바꾸지 않고 파생 결과만 따로 둔다. 분석 실패가 전사 결과를
무효로 만들지 않도록 Job 상태와 분리된 `analysis_status` 를 둔다.

기존 Job 은 분석을 돌린 적이 없으므로 'NONE' 으로 채워진다.

Revision ID: 4ee391a2fbe7
Revises: 9560319c7f96
Create Date: 2026-09-02 17:12:59.199465
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4ee391a2fbe7'
down_revision: str | None = '9560319c7f96'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stt_analysis',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('transcript_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('keywords', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('action_items', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('customer_reaction', sa.String(length=20), nullable=False),
    sa.Column('contact_classification', sa.String(length=20), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('opinion', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript_truncated', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['stt_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transcript_id'], ['stt_transcript.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_analysis_job')
    )
    with op.batch_alter_table('stt_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stt_analysis_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stt_analysis_job_id'), ['job_id'], unique=False)

    with op.batch_alter_table('stt_job', schema=None) as batch_op:
        # 기존 행을 채우기 위해 server_default 를 준 뒤 곧바로 제거한다. 남겨 두면
        # 애플리케이션이 값을 넘기지 않아도 통과해 기본값 의존이 숨는다.
        batch_op.add_column(
            sa.Column(
                'analysis_status', sa.String(length=20), nullable=False, server_default='NONE'
            )
        )
        batch_op.add_column(sa.Column('analysis_error_code', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###

    with op.batch_alter_table('stt_job', schema=None) as batch_op:
        batch_op.alter_column('analysis_status', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stt_job', schema=None) as batch_op:
        batch_op.drop_column('analysis_error_code')
        batch_op.drop_column('analysis_status')

    with op.batch_alter_table('stt_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stt_analysis_job_id'))
        batch_op.drop_index(batch_op.f('ix_stt_analysis_expires_at'))

    op.drop_table('stt_analysis')
    # ### end Alembic commands ###
