"""initial schema

전체 스키마와 audit_event Append-only 강제 (Harness §12 / §19).

`audit_event` 는 애플리케이션 계정이 INSERT 만 할 수 있어야 한다. ORM 계층이 UPDATE/DELETE
경로를 제공하지 않는 것만으로는 부족하다 — 버그나 직접 접속으로 우회 가능하기 때문이다.
DB 트리거로 이중 차단한다.

보관기간이 지난 감사 로그 삭제(Harness §21)는 이 트리거에도 막힌다. 의도된 것이며,
삭제가 필요하면 DBA 가 트리거를 일시 해제하고 그 사실 자체를 별도로 기록해야 한다.
애플리케이션 계정에는 어떤 경우에도 그 권한을 주지 않는다 (SEC-026).

Revision ID: 9560319c7f96
Revises:
Create Date: 2026-09-02 13:27:21.545250
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9560319c7f96'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# --- audit_event Append-only 강제 (Harness §19) --------------------------------

_PG_BLOCK_FUNCTION = """
CREATE OR REPLACE FUNCTION audit_event_block_modification()
RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_event is append-only (Harness 19)';
END;
$$ LANGUAGE plpgsql
"""

_PG_TRIGGERS = (
    """
    CREATE TRIGGER audit_event_no_update
    BEFORE UPDATE ON audit_event
    FOR EACH ROW EXECUTE FUNCTION audit_event_block_modification()
    """,
    """
    CREATE TRIGGER audit_event_no_delete
    BEFORE DELETE ON audit_event
    FOR EACH ROW EXECUTE FUNCTION audit_event_block_modification()
    """,
)

# SQLite 는 저장 프로시저가 없으므로 RAISE(ABORT) 를 직접 쓴다. 테스트 방언에서도 같은
# 보호가 걸려 있어야 "운영에서만 막힌다"는 상태를 피할 수 있다.
_SQLITE_TRIGGERS = (
    """
    CREATE TRIGGER audit_event_no_update
    BEFORE UPDATE ON audit_event
    BEGIN SELECT RAISE(ABORT, 'audit_event is append-only'); END
    """,
    """
    CREATE TRIGGER audit_event_no_delete
    BEFORE DELETE ON audit_event
    BEGIN SELECT RAISE(ABORT, 'audit_event is append-only'); END
    """,
)


def _create_append_only_triggers() -> None:
    dialect = op.get_bind().dialect.name
    if dialect == "postgresql":
        op.execute(_PG_BLOCK_FUNCTION)
        for statement in _PG_TRIGGERS:
            op.execute(statement)
    elif dialect == "sqlite":
        for statement in _SQLITE_TRIGGERS:
            op.execute(statement)
    else:
        # 조용히 넘어가면 감사 보호가 없는 채로 운영될 수 있다 (Harness §4.3).
        raise RuntimeError(
            f"audit append-only 트리거가 방언 '{dialect}' 에 대해 정의되지 않았다"
        )


def _drop_append_only_triggers() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_update ON audit_event")
    op.execute("DROP TRIGGER IF EXISTS audit_event_no_delete ON audit_event")
    op.execute("DROP FUNCTION IF EXISTS audit_event_block_modification()")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('USER','REVIEWER','ADMIN','AUDITOR')", name='ck_app_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip_masked', sa.String(length=64), nullable=False),
    sa.Column('application_version', sa.String(length=32), nullable=False),
    sa.Column('audio_sha256', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('stt_config_version', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(none_as_null=True).with_variant(postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_time', ['actor_id', 'event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_event_time'), ['event_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_job_id'), ['job_id'], unique=False)
        batch_op.create_index('ix_audit_event_type_time', ['event_type', 'event_time'], unique=False)

    op.create_table('config_change',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(length=64), nullable=False),
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_change_changed_at'), ['changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_change_config_key'), ['config_key'], unique=False)

    op.create_table('idempotency_record',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'actor_id')
    )
    op.create_table('runtime_config',
    sa.Column('config_key', sa.String(length=128), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('stt_job',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('audio_relpath', sa.String(length=512), nullable=True),
    sa.Column('audio_sha256', sa.String(length=64), nullable=False),
    sa.Column('audio_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('audio_duration_seconds', sa.Float(), nullable=True),
    sa.Column('audio_content_type', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('model_artifact_hash', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('detected_language', sa.String(length=16), nullable=True),
    sa.Column('beam_size', sa.Integer(), nullable=False),
    sa.Column('vad_enabled', sa.Boolean(), nullable=False),
    sa.Column('compute_type', sa.String(length=32), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('preprocessor_version', sa.String(length=32), nullable=False),
    sa.Column('normalizer_version', sa.String(length=32), nullable=False),
    sa.Column('application_version', sa.String(length=32), nullable=False),
    sa.Column('stt_config_version', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_wait_seconds', sa.Float(), nullable=True),
    sa.Column('processing_duration_seconds', sa.Float(), nullable=True),
    sa.Column('real_time_factor', sa.Float(), nullable=True),
    sa.Column('audio_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by', 'idempotency_key', name='uq_job_owner_idempotency')
    )
    with op.batch_alter_table('stt_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stt_job_audio_expires_at'), ['audio_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stt_job_audio_sha256'), ['audio_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_stt_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_stt_job_owner_created', ['created_by', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stt_job_status'), ['status'], unique=False)

    op.create_table('stt_transcript',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('storage_relpath', sa.String(length=512), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('segment_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('processor', sa.String(length=64), nullable=False),
    sa.Column('processor_version', sa.String(length=32), nullable=False),
    sa.Column('input_transcript_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('RAW','NORMALIZED','LLM_CORRECTED')", name='ck_transcript_kind'),
    sa.ForeignKeyConstraint(['input_transcript_id'], ['stt_transcript.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['stt_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'kind', name='uq_transcript_job_kind')
    )
    with op.batch_alter_table('stt_transcript', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stt_transcript_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stt_transcript_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###

    _create_append_only_triggers()


def downgrade() -> None:
    # 트리거를 먼저 제거해야 테이블을 지울 수 있다.
    if op.get_bind().dialect.name == "postgresql":
        _drop_append_only_triggers()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stt_transcript', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stt_transcript_job_id'))
        batch_op.drop_index(batch_op.f('ix_stt_transcript_expires_at'))

    op.drop_table('stt_transcript')
    with op.batch_alter_table('stt_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stt_job_status'))
        batch_op.drop_index('ix_stt_job_owner_created')
        batch_op.drop_index(batch_op.f('ix_stt_job_created_at'))
        batch_op.drop_index(batch_op.f('ix_stt_job_audio_sha256'))
        batch_op.drop_index(batch_op.f('ix_stt_job_audio_expires_at'))

    op.drop_table('stt_job')
    op.drop_table('runtime_config')
    op.drop_table('idempotency_record')
    with op.batch_alter_table('config_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_change_config_key'))
        batch_op.drop_index(batch_op.f('ix_config_change_changed_at'))

    op.drop_table('config_change')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_event_type_time')
        batch_op.drop_index(batch_op.f('ix_audit_event_job_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_event_time'))
        batch_op.drop_index(batch_op.f('ix_audit_event_actor_id'))
        batch_op.drop_index('ix_audit_actor_time')

    op.drop_table('audit_event')
    op.drop_table('app_user')
    # ### end Alembic commands ###
